#!/usr/bin/env python3

import os
import sys

def find_ttfs(input):
    files = []
    for path in input:
        if os.path.isdir(path):
            for file in os.listdir(path):
                if file.lower().endswith(".ttf"):
                    files.append(os.path.join(path, file))
        elif os.path.isfile(path) and path.lower().endswith(".ttf"):
            files.append(path)
    return files


def classify(path):
    name = os.path.basename(path).lower()
    if "bold" in name and "italic" not in name:
        return "bold"
    elif "italic" in name and "bold" not in name:
        return "italic"
    return "regular"


def emit_array(out, symbol, data):
    out.write("static const unsigned char %s[] = {\n" % symbol)
    per_line = 20
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        out.write("    " + ", ".join(str(b) for b in chunk) + ",\n")
    out.write("};\n")
    out.write("#define %s_LEN ((int)sizeof(%s))\n\n" % (symbol, symbol));


def main(argv):
    if len(argv) < 3:
        print("Usage: embed_font.py <output.h> <font.ttf|dir> [more ...]", file=sys.stderr)
        return 2;

    out_path = argv[1]
    ttfs = find_ttfs(argv[2:])
    slots = {"regular": None, "bold": None, "italic": None}

    for path in ttfs:
        slot = classify(path)
        slots[slot] = path

    if slots["regular"] is None:
        print(f"no Regular font found among inputs", file=sys.stderr)
        return 1

    with open(out_path, "w") as out:
        out.write("/* Generated by scripts/embed_font.py - do NOT edit. */\n")
        out.write("#ifndef RV_FONTS_H\n#define RV_FONTS_H\n\n")

        with open(slots["regular"], "rb") as f:
            emit_array(out, "FONT_REGULAR", f.read())

        for slot, symbol in (("bold", "FONT_BOLD"), ("italic", "FONT_ITALIC")):
            if slots[slot] is not None:
                with open(slots[slot], "rb") as f:
                    emit_array(out, symbol, f.read())
            else:
                out.write(f"// No {slot} font supplied; falling back to regualr\n")
                out.write(f"#define {symbol} FONT_REGULAR\n")
                out.write(f"#define {symbol}_LEN FONT_REGULAR_LEN\n\n")

        out.write("#endif /* RV_FONTS_H */\n")

    chosen = ", ".join(f"{slot}={os.path.basename(p) if p else '(regular)'}" for slot, p in slots.items());

    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv))
